apiVersion: v1
kind: ServiceAccount
metadata:
  name: garage
automountServiceAccountToken: false
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: garage
  labels:
    app: garage
    owner: "RedbackRacing"
  annotations:
    email: "info@redbackracing63.com"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: garage
  template:
    metadata:
      labels:
        app: garage
    spec:
      serviceAccountName: garage
      containers:
        - name: garage
          image: "redbackracing/garage_service:v2.0.3"
          imagePullPolicy: "IfNotPresent"
          env:
            - name: DB_PROVIDER
              value: "postgres"
            - name: DB_HOSTNAME
              valueFrom:
                configMapKeyRef:
                  name: postres
                  key: endpoint
            - name: DB_PORT
              value: "5432"
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: garage-service
                  key: database
            - name: DB_USER
              valueFrom:
                configMapKeyRef:
                  name: garage-service
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: garage-service
                  key: password
          resources:
            requests:
              memory: 16Mi
              cpu: 10m
            limits:
              memory: 128Mi
              cpu: 100m
          securityContext:
            runAsNonRoot: true
            readOnlyRootFilesystem: true
            runAsUser: 1000
          readinessProbe:
            httpGet:
              path: /healthcheck
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /healthcheck
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 10
          startupProbe:
            httpGet:
              path: /healthcheck
              port: 8000
            failureThreshold: 60
            periodSeconds: 10
            initialDelaySeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: garage-service
  labels:
    app: garage
spec:
  selector:
    app: garage
  ports:
    - port: 8000
      protocol: TCP
      targetPort: 8000
